//
// BroadcastInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BroadcastInput: Codable {
    public var chainId: String
    public var rawTransaction: String

    public init(chainId: String, rawTransaction: String) {
        self.chainId = chainId
        self.rawTransaction = rawTransaction
    }
}
