//
// BroadCastRawTransactionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BroadCastRawTransactionResponse: Codable {
    public var success: Bool
    public var message: String
    public var data: String

    public init(success: Bool, message: String, data: String) {
        self.success = success
        self.message = message
        self.data = data
    }
}
