//
// ConveyorFinanceControllerResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConveyorFinanceControllerResponse: Codable {
    public var input: InputBody?
    public var convey: TransactionResponse?
    public var data: Transaction?
    public var tx: TransactionResponseTx?
    public var signed: Transaction?
    public var success: Bool
    public var message: String

    public init(input: InputBody? = nil, convey: TransactionResponse? = nil, data: Transaction? = nil, tx: TransactionResponseTx? = nil, signed: Transaction? = nil, success: Bool, message: String) {
        self.input = input
        self.convey = convey
        self.data = data
        self.tx = tx
        self.signed = signed
        self.success = success
        self.message = message
    }
}
