//
// CreateAccountInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateAccountInput: Codable {
    public var privateKey: String?

    public init(privateKey: String? = nil) {
        self.privateKey = privateKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case privateKey = "private_key"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        privateKey = try container.decodeIfPresent(String.self, forKey: .privateKey)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(privateKey, forKey: .privateKey)
    }
}
