//
// GetSupportedOnRampsResponseMessageInnerIconsPng.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetSupportedOnRampsResponseMessageInnerIconsPng: Codable {
    public var _160x160: String
    public var _32x32: String

    public init(_160x160: String, _32x32: String) {
        self._160x160 = _160x160
        self._32x32 = _32x32
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _160x160 = "160x160"
        case _32x32 = "32x32"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        _160x160 = try container.decode(String.self, forKey: ._160x160)
        _32x32 = try container.decode(String.self, forKey: ._32x32)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(_160x160, forKey: ._160x160)
        try container.encode(_32x32, forKey: ._32x32)
    }
}
