//
// GetSupportedOnRampsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetSupportedOnRampsResponse: Codable {
    public var message: [GetSupportedOnRampsResponseMessageInner]

    public init(message: [GetSupportedOnRampsResponseMessageInner]) {
        self.message = message
    }
}
