//
// GetSupportedOnRampsResponseMessageInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetSupportedOnRampsResponseMessageInner: Codable {
    public var id: String
    public var displayName: String
    public var icons: GetSupportedOnRampsResponseMessageInnerIcons
    public var icon: String

    public init(id: String, displayName: String, icons: GetSupportedOnRampsResponseMessageInnerIcons, icon: String) {
        self.id = id
        self.displayName = displayName
        self.icons = icons
        self.icon = icon
    }
}
