//
// GetSupportedOnRampsResponseMessageInnerIcons.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetSupportedOnRampsResponseMessageInnerIcons: Codable {
    public var png: GetSupportedOnRampsResponseMessageInnerIconsPng
    public var svg: String

    public init(png: GetSupportedOnRampsResponseMessageInnerIconsPng, svg: String) {
        self.png = png
        self.svg = svg
    }
}
