//
// GetSwapDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetSwapDto: Codable {
    public var src: String
    public var dst: String
    public var amount: String
    public var from: String
    public var slippage: Double
    public var protocols: String?
    public var fee: String?
    public var disableEstimate: Bool?
    public var permit: String?
    public var includeTokensInfo: Bool?
    public var includeProtocols: Bool?
    public var compatibility: Bool?
    public var allowPartialFill: Bool?
    public var parts: String?
    public var mainRouteParts: String?
    public var connectorTokens: String?
    public var complexityLevel: String?
    public var gasLimit: String?
    public var gasPrice: String?
    public var referrer: String?
    public var receiver: String?
    public var chainId: Double?

    public init(src: String, dst: String, amount: String, from: String, slippage: Double, protocols: String? = nil, fee: String? = nil, disableEstimate: Bool? = nil, permit: String? = nil, includeTokensInfo: Bool? = nil, includeProtocols: Bool? = nil, compatibility: Bool? = nil, allowPartialFill: Bool? = nil, parts: String? = nil, mainRouteParts: String? = nil, connectorTokens: String? = nil, complexityLevel: String? = nil, gasLimit: String? = nil, gasPrice: String? = nil, referrer: String? = nil, receiver: String? = nil, chainId: Double? = nil) {
        self.src = src
        self.dst = dst
        self.amount = amount
        self.from = from
        self.slippage = slippage
        self.protocols = protocols
        self.fee = fee
        self.disableEstimate = disableEstimate
        self.permit = permit
        self.includeTokensInfo = includeTokensInfo
        self.includeProtocols = includeProtocols
        self.compatibility = compatibility
        self.allowPartialFill = allowPartialFill
        self.parts = parts
        self.mainRouteParts = mainRouteParts
        self.connectorTokens = connectorTokens
        self.complexityLevel = complexityLevel
        self.gasLimit = gasLimit
        self.gasPrice = gasPrice
        self.referrer = referrer
        self.receiver = receiver
        self.chainId = chainId
    }
}
