//
// InternalTransaction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InternalTransaction: Codable {
    public var from: String?
    public var to: String?
    public var value: String?
    public var transactionHash: String
    public var gas: String?

    public init(from: String?, to: String?, value: String?, transactionHash: String, gas: String?) {
        self.from = from
        self.to = to
        self.value = value
        self.transactionHash = transactionHash
        self.gas = gas
    }
}
