//
// IWebhook.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct IWebhook: Codable {
    public var block: Block
    public var chainId: String
    public var logs: [Log]
    public var txs: [Transaction]
    public var txsInternal: [InternalTransaction]
    public var abi: [AbiItem]
    public var retries: Double
    public var confirmed: Bool
    public var tag: String
    public var streamId: String
    public var erc20Transfers: [IERC20Transfer]
    public var erc20Approvals: [IERC20Approval]
    public var nftTransfers: [INFTTransfer]
    public var nativeBalances: [INativeBalance]
    public var nftApprovals: IOldNFTApproval
    public var nftTokenApprovals: [INFTApproval]

    public init(block: Block, chainId: String, logs: [Log], txs: [Transaction], txsInternal: [InternalTransaction], abi: [AbiItem], retries: Double, confirmed: Bool, tag: String, streamId: String, erc20Transfers: [IERC20Transfer], erc20Approvals: [IERC20Approval], nftTransfers: [INFTTransfer], nativeBalances: [INativeBalance], nftApprovals: IOldNFTApproval, nftTokenApprovals: [INFTApproval]) {
        self.block = block
        self.chainId = chainId
        self.logs = logs
        self.txs = txs
        self.txsInternal = txsInternal
        self.abi = abi
        self.retries = retries
        self.confirmed = confirmed
        self.tag = tag
        self.streamId = streamId
        self.erc20Transfers = erc20Transfers
        self.erc20Approvals = erc20Approvals
        self.nftTransfers = nftTransfers
        self.nativeBalances = nativeBalances
        self.nftApprovals = nftApprovals
        self.nftTokenApprovals = nftTokenApprovals
    }
}
