//
// Log.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Log: Codable {
    public var triggers: [TriggerOutput]?
    public var logIndex: String
    public var transactionHash: String
    public var address: String
    public var data: String
    public var topic0: String?
    public var topic1: String?
    public var topic2: String?
    public var topic3: String?

    public init(triggers: [TriggerOutput]? = nil, logIndex: String, transactionHash: String, address: String, data: String, topic0: String?, topic1: String?, topic2: String?, topic3: String?) {
        self.triggers = triggers
        self.logIndex = logIndex
        self.transactionHash = transactionHash
        self.address = address
        self.data = data
        self.topic0 = topic0
        self.topic1 = topic1
        self.topic2 = topic2
        self.topic3 = topic3
    }
}
