//
// SupportedDefaultResponseDefaults.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SupportedDefaultResponseDefaults: Codable {
    public var id: SupportedDefaultResponseDefaultsId

    public init(id: SupportedDefaultResponseDefaultsId) {
        self.id = id
    }
}
