//
// SupportedPaymentTypesCurrencyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SupportedPaymentTypesCurrencyResponse: Codable {
    public var message: SupportedPaymentTypesMessage

    public init(message: SupportedPaymentTypesMessage) {
        self.message = message
    }
}
