//
// SupportedAssetResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SupportedAssetResponse: Codable {
    public var country: String
    public var assets: [SupportedAssetResponseAssetsInner]

    public init(country: String, assets: [SupportedAssetResponseAssetsInner]) {
        self.country = country
        self.assets = assets
    }
}
