//
// TransactionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TransactionRequest: Codable {
    public var nonce: String?
    public var data: String?
    public var value: String?
    public var to: String?
    public var from: String?
    public var maxFeePerGas: String?
    public var maxPriorityFeePerGas: String?

    public init(nonce: String? = nil, data: String? = nil, value: String? = nil, to: String? = nil, from: String? = nil, maxFeePerGas: String? = nil, maxPriorityFeePerGas: String? = nil) {
        self.nonce = nonce
        self.data = data
        self.value = value
        self.to = to
        self.from = from
        self.maxFeePerGas = maxFeePerGas
        self.maxPriorityFeePerGas = maxPriorityFeePerGas
    }
}
