//
// TransactionInputSupportedParamsPartnerDataRedirectUrl.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TransactionInputSupportedParamsPartnerDataRedirectUrl: Codable {
    public var success: String

    public init(success: String) {
        self.success = success
    }
}
