//
// TransactionResponseTx.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TransactionResponseTx: Codable {
    public var data: String
    public var value: String
    public var nonce: Double
    public var gas: String
    public var to: String
    public var from: String

    public init(data: String, value: String, nonce: Double, gas: String, to: String, from: String) {
        self.data = data
        self.value = value
        self.nonce = nonce
        self.gas = gas
        self.to = to
        self.from = from
    }
}
