//
// TransactionInputWallet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TransactionInputWallet: Codable {
    public var address: String

    public init(address: String) {
        self.address = address
    }
}
