//
// TransactionInputMetaData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TransactionInputMetaData: Codable {
    public var quoteId: String

    public init(quoteId: String) {
        self.quoteId = quoteId
    }
}
