//
// TransactionInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TransactionInput: Codable {
    public var supportedParams: TransactionInputSupportedParams
    public var wallet: TransactionInputWallet
    public var metaData: TransactionInputMetaData
    public var originatingHost: String
    public var partnerContext: String
    public var uuid: String
    public var network: String
    public var paymentMethod: String
    public var type: String
    public var amount: Double
    public var destination: String
    public var source: String
    public var onramp: String

    public init(supportedParams: TransactionInputSupportedParams, wallet: TransactionInputWallet, metaData: TransactionInputMetaData, originatingHost: String, partnerContext: String, uuid: String, network: String, paymentMethod: String, type: String, amount: Double, destination: String, source: String, onramp: String) {
        self.supportedParams = supportedParams
        self.wallet = wallet
        self.metaData = metaData
        self.originatingHost = originatingHost
        self.partnerContext = partnerContext
        self.uuid = uuid
        self.network = network
        self.paymentMethod = paymentMethod
        self.type = type
        self.amount = amount
        self.destination = destination
        self.source = source
        self.onramp = onramp
    }
}
