//
// TriggerOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TriggerOutput: Codable {
    public var value: Any?
    public var name: String

    public init(value: Any?, name: String) {
        self.value = value
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case name
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        value = try container.decode(Any.self, forKey: .value)
        name = try container.decode(String.self, forKey: .name)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(try JSONSerialization.data(withJSONObject: value), forKey: .value)
        try container.encode(name, forKey: .name)
    }
}
