//
// Block.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Block: Codable, JSONEncodable, Hashable {

    public var number: String
    public var hash: String
    public var timestamp: String

    public init(number: String, hash: String, timestamp: String) {
        self.number = number
        self.hash = hash
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case number
        case hash
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(number, forKey: .number)
        try container.encode(hash, forKey: .hash)
        try container.encode(timestamp, forKey: .timestamp)
    }
}

