//
// BroadcastInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BroadcastInput: Codable, JSONEncodable, Hashable {

    public var chainId: String
    public var rawTransaction: String

    public init(chainId: String, rawTransaction: String) {
        self.chainId = chainId
        self.rawTransaction = rawTransaction
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chainId
        case rawTransaction
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(chainId, forKey: .chainId)
        try container.encode(rawTransaction, forKey: .rawTransaction)
    }
}

