//
// FiatCurrency.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FiatCurrency: Codable, JSONEncodable, Hashable {

    public var icon: String
    public var symbol: String
    public var name: String
    public var code: String
    public var id: String

    public init(icon: String, symbol: String, name: String, code: String, id: String) {
        self.icon = icon
        self.symbol = symbol
        self.name = name
        self.code = code
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case icon
        case symbol
        case name
        case code
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(icon, forKey: .icon)
        try container.encode(symbol, forKey: .symbol)
        try container.encode(name, forKey: .name)
        try container.encode(code, forKey: .code)
        try container.encode(id, forKey: .id)
    }
}

