//
// INFTTransfer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct INFTTransfer: Codable, JSONEncodable, Hashable {

    public var transactionHash: String
    public var contract: String
    public var logIndex: String
    public var tokenContractType: String
    public var tokenName: String
    public var tokenSymbol: String
    public var triggers: [TriggerOutput]?
    public var _operator: String?
    public var from: String
    public var to: String
    public var tokenId: String
    public var amount: String

    public init(transactionHash: String, contract: String, logIndex: String, tokenContractType: String, tokenName: String, tokenSymbol: String, triggers: [TriggerOutput]? = nil, _operator: String?, from: String, to: String, tokenId: String, amount: String) {
        self.transactionHash = transactionHash
        self.contract = contract
        self.logIndex = logIndex
        self.tokenContractType = tokenContractType
        self.tokenName = tokenName
        self.tokenSymbol = tokenSymbol
        self.triggers = triggers
        self._operator = _operator
        self.from = from
        self.to = to
        self.tokenId = tokenId
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transactionHash
        case contract
        case logIndex
        case tokenContractType
        case tokenName
        case tokenSymbol
        case triggers
        case _operator = "operator"
        case from
        case to
        case tokenId
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(transactionHash, forKey: .transactionHash)
        try container.encode(contract, forKey: .contract)
        try container.encode(logIndex, forKey: .logIndex)
        try container.encode(tokenContractType, forKey: .tokenContractType)
        try container.encode(tokenName, forKey: .tokenName)
        try container.encode(tokenSymbol, forKey: .tokenSymbol)
        try container.encodeIfPresent(triggers, forKey: .triggers)
        try container.encode(_operator, forKey: ._operator)
        try container.encode(from, forKey: .from)
        try container.encode(to, forKey: .to)
        try container.encode(tokenId, forKey: .tokenId)
        try container.encode(amount, forKey: .amount)
    }
}

