//
// INFTApprovalERC721.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct INFTApprovalERC721: Codable, JSONEncodable, Hashable {

    public var transactionHash: String
    public var contract: String
    public var logIndex: String
    public var owner: String
    public var approved: String
    public var tokenId: String
    public var tokenContractType: String
    public var tokenName: String
    public var tokenSymbol: String

    public init(transactionHash: String, contract: String, logIndex: String, owner: String, approved: String, tokenId: String, tokenContractType: String, tokenName: String, tokenSymbol: String) {
        self.transactionHash = transactionHash
        self.contract = contract
        self.logIndex = logIndex
        self.owner = owner
        self.approved = approved
        self.tokenId = tokenId
        self.tokenContractType = tokenContractType
        self.tokenName = tokenName
        self.tokenSymbol = tokenSymbol
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transactionHash
        case contract
        case logIndex
        case owner
        case approved
        case tokenId
        case tokenContractType
        case tokenName
        case tokenSymbol
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(transactionHash, forKey: .transactionHash)
        try container.encode(contract, forKey: .contract)
        try container.encode(logIndex, forKey: .logIndex)
        try container.encode(owner, forKey: .owner)
        try container.encode(approved, forKey: .approved)
        try container.encode(tokenId, forKey: .tokenId)
        try container.encode(tokenContractType, forKey: .tokenContractType)
        try container.encode(tokenName, forKey: .tokenName)
        try container.encode(tokenSymbol, forKey: .tokenSymbol)
    }
}

