//
// NonceResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NonceResponse: Codable, JSONEncodable, Hashable {

    public var nonce: Double

    public init(nonce: Double) {
        self.nonce = nonce
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nonce
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nonce, forKey: .nonce)
    }
}

