//
// SupportedAssetResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SupportedAssetResponse: Codable, JSONEncodable, Hashable {

    public var country: String
    public var assets: [SupportedAssetResponseAssetsInner]

    public init(country: String, assets: [SupportedAssetResponseAssetsInner]) {
        self.country = country
        self.assets = assets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case country
        case assets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(country, forKey: .country)
        try container.encode(assets, forKey: .assets)
    }
}

