//
// SupportedDefaultResponseDefaultsId.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SupportedDefaultResponseDefaultsId: Codable, JSONEncodable, Hashable {

    public var provider: String
    public var paymentMethod: String
    public var amount: Double
    public var target: String
    public var source: String

    public init(provider: String, paymentMethod: String, amount: Double, target: String, source: String) {
        self.provider = provider
        self.paymentMethod = paymentMethod
        self.amount = amount
        self.target = target
        self.source = source
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case paymentMethod
        case amount
        case target
        case source
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(provider, forKey: .provider)
        try container.encode(paymentMethod, forKey: .paymentMethod)
        try container.encode(amount, forKey: .amount)
        try container.encode(target, forKey: .target)
        try container.encode(source, forKey: .source)
    }
}

