//
// TokenSwapParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TokenSwapParams: Codable, JSONEncodable, Hashable {

    public var to: String?
    public var data: String?
    public var input: String?
    public var value: String?
    public var nonce: String?
    public var gas: String?
    public var gasPrice: String?
    public var chainId: String?
    public var encoding: String?
    public var EOA: Bool?
    public var contractAddress: String?
    public var tokenId: String?
    public var tokenIds: String?
    public var approved: Bool?
    public var broadcast: Bool?
    public var tokenIn: String
    public var tokenOut: String
    public var tokenInDecimals: Double
    public var tokenOutDecimals: Double
    public var amountIn: String
    public var slippage: String
    public var recipient: String
    public var referrer: String

    public init(to: String? = nil, data: String? = nil, input: String? = nil, value: String? = nil, nonce: String? = nil, gas: String? = nil, gasPrice: String? = nil, chainId: String? = nil, encoding: String? = nil, EOA: Bool? = nil, contractAddress: String? = nil, tokenId: String? = nil, tokenIds: String? = nil, approved: Bool? = nil, broadcast: Bool? = nil, tokenIn: String, tokenOut: String, tokenInDecimals: Double, tokenOutDecimals: Double, amountIn: String, slippage: String, recipient: String, referrer: String) {
        self.to = to
        self.data = data
        self.input = input
        self.value = value
        self.nonce = nonce
        self.gas = gas
        self.gasPrice = gasPrice
        self.chainId = chainId
        self.encoding = encoding
        self.EOA = EOA
        self.contractAddress = contractAddress
        self.tokenId = tokenId
        self.tokenIds = tokenIds
        self.approved = approved
        self.broadcast = broadcast
        self.tokenIn = tokenIn
        self.tokenOut = tokenOut
        self.tokenInDecimals = tokenInDecimals
        self.tokenOutDecimals = tokenOutDecimals
        self.amountIn = amountIn
        self.slippage = slippage
        self.recipient = recipient
        self.referrer = referrer
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case to
        case data
        case input
        case value
        case nonce
        case gas
        case gasPrice
        case chainId = "chain_id"
        case encoding
        case EOA
        case contractAddress = "contract_address"
        case tokenId = "token_id"
        case tokenIds = "token_ids"
        case approved
        case broadcast
        case tokenIn
        case tokenOut
        case tokenInDecimals
        case tokenOutDecimals
        case amountIn
        case slippage
        case recipient
        case referrer
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(to, forKey: .to)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(input, forKey: .input)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(nonce, forKey: .nonce)
        try container.encodeIfPresent(gas, forKey: .gas)
        try container.encodeIfPresent(gasPrice, forKey: .gasPrice)
        try container.encodeIfPresent(chainId, forKey: .chainId)
        try container.encodeIfPresent(encoding, forKey: .encoding)
        try container.encodeIfPresent(EOA, forKey: .EOA)
        try container.encodeIfPresent(contractAddress, forKey: .contractAddress)
        try container.encodeIfPresent(tokenId, forKey: .tokenId)
        try container.encodeIfPresent(tokenIds, forKey: .tokenIds)
        try container.encodeIfPresent(approved, forKey: .approved)
        try container.encodeIfPresent(broadcast, forKey: .broadcast)
        try container.encode(tokenIn, forKey: .tokenIn)
        try container.encode(tokenOut, forKey: .tokenOut)
        try container.encode(tokenInDecimals, forKey: .tokenInDecimals)
        try container.encode(tokenOutDecimals, forKey: .tokenOutDecimals)
        try container.encode(amountIn, forKey: .amountIn)
        try container.encode(slippage, forKey: .slippage)
        try container.encode(recipient, forKey: .recipient)
        try container.encode(referrer, forKey: .referrer)
    }
}

