//
// Transaction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Transaction: Codable, JSONEncodable, Hashable {

    public var useropTransaction: String?
    public var userOps: [TransactionRequest]?
    public var transaction: Tx?
    public var signature: String?
    public var moonScanUrl: String?
    public var transactions: [TransactionData]?
    public var data: String?
    public var rawTransaction: String?
    public var signedTransaction: String?
    public var transactionHash: String?

    public init(useropTransaction: String? = nil, userOps: [TransactionRequest]? = nil, transaction: Tx? = nil, signature: String? = nil, moonScanUrl: String? = nil, transactions: [TransactionData]? = nil, data: String? = nil, rawTransaction: String? = nil, signedTransaction: String? = nil, transactionHash: String? = nil) {
        self.useropTransaction = useropTransaction
        self.userOps = userOps
        self.transaction = transaction
        self.signature = signature
        self.moonScanUrl = moonScanUrl
        self.transactions = transactions
        self.data = data
        self.rawTransaction = rawTransaction
        self.signedTransaction = signedTransaction
        self.transactionHash = transactionHash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case useropTransaction = "userop_transaction"
        case userOps
        case transaction
        case signature
        case moonScanUrl = "moon_scan_url"
        case transactions
        case data
        case rawTransaction = "raw_transaction"
        case signedTransaction = "signed_transaction"
        case transactionHash = "transaction_hash"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(useropTransaction, forKey: .useropTransaction)
        try container.encodeIfPresent(userOps, forKey: .userOps)
        try container.encodeIfPresent(transaction, forKey: .transaction)
        try container.encodeIfPresent(signature, forKey: .signature)
        try container.encodeIfPresent(moonScanUrl, forKey: .moonScanUrl)
        try container.encodeIfPresent(transactions, forKey: .transactions)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(rawTransaction, forKey: .rawTransaction)
        try container.encodeIfPresent(signedTransaction, forKey: .signedTransaction)
        try container.encodeIfPresent(transactionHash, forKey: .transactionHash)
    }
}

