//
// TransactionInputSupportedParamsPartnerData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionInputSupportedParamsPartnerData: Codable, JSONEncodable, Hashable {

    public var redirectUrl: TransactionInputSupportedParamsPartnerDataRedirectUrl

    public init(redirectUrl: TransactionInputSupportedParamsPartnerDataRedirectUrl) {
        self.redirectUrl = redirectUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case redirectUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(redirectUrl, forKey: .redirectUrl)
    }
}

