//
// TransactionResponseInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionResponseInfo: Codable, JSONEncodable, Hashable {

    public var conveyorGas: String
    public var affiliateGas: String
    public var affiliateAggregator: String
    public var amountOut: String
    public var amountOutMin: String

    public init(conveyorGas: String, affiliateGas: String, affiliateAggregator: String, amountOut: String, amountOutMin: String) {
        self.conveyorGas = conveyorGas
        self.affiliateGas = affiliateGas
        self.affiliateAggregator = affiliateAggregator
        self.amountOut = amountOut
        self.amountOutMin = amountOutMin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case conveyorGas
        case affiliateGas
        case affiliateAggregator
        case amountOut
        case amountOutMin
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(conveyorGas, forKey: .conveyorGas)
        try container.encode(affiliateGas, forKey: .affiliateGas)
        try container.encode(affiliateAggregator, forKey: .affiliateAggregator)
        try container.encode(amountOut, forKey: .amountOut)
        try container.encode(amountOutMin, forKey: .amountOutMin)
    }
}

