//
// TransactionInputSupportedParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionInputSupportedParams: Codable, JSONEncodable, Hashable {

    public var partnerData: TransactionInputSupportedParamsPartnerData
    public var theme: TransactionInputSupportedParamsTheme

    public init(partnerData: TransactionInputSupportedParamsPartnerData, theme: TransactionInputSupportedParamsTheme) {
        self.partnerData = partnerData
        self.theme = theme
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case partnerData
        case theme
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(partnerData, forKey: .partnerData)
        try container.encode(theme, forKey: .theme)
    }
}

